# Prometheus Alerting Rules for Enterprise Authentication Backend
# These rules define critical alerts for system monitoring and incident response

groups:
  - name: auth-backend-critical
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: rate(auth_backend_http_requests_total{status_code=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: auth-backend
          category: availability
        annotations:
          summary: "High error rate detected in authentication backend"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes, which is above the 10% threshold."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/high-error-rate"

      # Authentication Failure Spike
      - alert: AuthenticationFailureSpike
        expr: rate(auth_backend_authentication_attempts_total{status="failure"}[5m]) > 10
        for: 1m
        labels:
          severity: critical
          service: auth-backend
          category: security
        annotations:
          summary: "Spike in authentication failures detected"
          description: "Authentication failure rate is {{ $value }} failures/second, indicating potential security attack."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/auth-failure-spike"

      # Service Down Alert
      - alert: ServiceDown
        expr: up{job="auth-backend"} == 0
        for: 1m
        labels:
          severity: critical
          service: auth-backend
          category: availability
        annotations:
          summary: "Authentication backend service is down"
          description: "The authentication backend service has been down for more than 1 minute."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/service-down"

      # Database Connection Failure
      - alert: DatabaseConnectionFailure
        expr: auth_backend_health_check_status{check_name="database"} != 2
        for: 30s
        labels:
          severity: critical
          service: auth-backend
          category: infrastructure
        annotations:
          summary: "Database connection failure"
          description: "Database health check is failing. Status: {{ $value }}"
          runbook_url: "https://docs.company.com/runbooks/auth-backend/database-failure"

      # Redis Connection Failure
      - alert: RedisConnectionFailure
        expr: auth_backend_health_check_status{check_name="redis"} != 2
        for: 1m
        labels:
          severity: warning
          service: auth-backend
          category: infrastructure
        annotations:
          summary: "Redis connection failure"
          description: "Redis health check is failing. Status: {{ $value }}"
          runbook_url: "https://docs.company.com/runbooks/auth-backend/redis-failure"

  - name: auth-backend-performance
    rules:
      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(auth_backend_authentication_duration_seconds_bucket[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          service: auth-backend
          category: performance
        annotations:
          summary: "High authentication response time"
          description: "95th percentile response time is {{ $value | humanizeDuration }}, exceeding 100ms threshold."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/high-response-time"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes{job="auth-backend"} / 1024 / 1024) > 1024
        for: 5m
        labels:
          severity: warning
          service: auth-backend
          category: resources
        annotations:
          summary: "High memory usage in authentication backend"
          description: "Memory usage is {{ $value }}MB, exceeding 1GB threshold."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/high-memory-usage"

      # High CPU Usage
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total{job="auth-backend"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: auth-backend
          category: resources
        annotations:
          summary: "High CPU usage in authentication backend"
          description: "CPU usage is {{ $value | humanizePercentage }}, exceeding 80% threshold."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/high-cpu-usage"

      # Low Cache Hit Rate
      - alert: LowCacheHitRate
        expr: auth_backend_cache_hit_ratio < 0.8
        for: 10m
        labels:
          severity: warning
          service: auth-backend
          category: performance
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate for {{ $labels.cache_type }} is {{ $value | humanizePercentage }}, below 80% threshold."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/low-cache-hit-rate"

  - name: auth-backend-security
    rules:
      # Suspicious Activity Alert
      - alert: SuspiciousActivity
        expr: rate(auth_backend_suspicious_activities_total[5m]) > 1
        for: 1m
        labels:
          severity: warning
          service: auth-backend
          category: security
        annotations:
          summary: "Suspicious activity detected"
          description: "Suspicious activity rate is {{ $value }} events/second for activity type {{ $labels.activity_type }}."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/suspicious-activity"

      # Account Lockout Spike
      - alert: AccountLockoutSpike
        expr: rate(auth_backend_account_lockouts_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: auth-backend
          category: security
        annotations:
          summary: "High rate of account lockouts"
          description: "Account lockout rate is {{ $value }} lockouts/second, indicating potential brute force attack."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/account-lockout-spike"

      # High Risk Score Events
      - alert: HighRiskScoreEvents
        expr: rate(auth_backend_risk_scores_bucket{le="0.8"}[5m]) < rate(auth_backend_risk_scores_count[5m]) * 0.9
        for: 5m
        labels:
          severity: warning
          service: auth-backend
          category: security
        annotations:
          summary: "High proportion of high-risk events"
          description: "More than 10% of events have risk scores above 0.8, indicating potential security threats."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/high-risk-events"

      # Rate Limiting Triggered
      - alert: RateLimitingTriggered
        expr: rate(auth_backend_rate_limit_hits_total[5m]) > 10
        for: 2m
        labels:
          severity: info
          service: auth-backend
          category: security
        annotations:
          summary: "Rate limiting frequently triggered"
          description: "Rate limiting is being triggered {{ $value }} times/second for endpoint {{ $labels.endpoint }}."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/rate-limiting-triggered"

  - name: auth-backend-business
    rules:
      # Low Authentication Success Rate
      - alert: LowAuthenticationSuccessRate
        expr: |
          (
            rate(auth_backend_authentication_attempts_total{status="success"}[10m]) /
            rate(auth_backend_authentication_attempts_total[10m])
          ) < 0.9
        for: 5m
        labels:
          severity: warning
          service: auth-backend
          category: business
        annotations:
          summary: "Low authentication success rate"
          description: "Authentication success rate is {{ $value | humanizePercentage }}, below 90% threshold."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/low-success-rate"

      # Session Duration Anomaly
      - alert: SessionDurationAnomaly
        expr: |
          histogram_quantile(0.95, rate(auth_backend_session_duration_seconds_bucket[1h])) > 86400
        for: 10m
        labels:
          severity: info
          service: auth-backend
          category: business
        annotations:
          summary: "Unusually long session durations detected"
          description: "95th percentile session duration is {{ $value | humanizeDuration }}, exceeding 24 hours."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/session-duration-anomaly"

  - name: auth-backend-infrastructure
    rules:
      # Circuit Breaker Open
      - alert: CircuitBreakerOpen
        expr: auth_backend_circuit_breaker_state == 2
        for: 1m
        labels:
          severity: warning
          service: auth-backend
          category: infrastructure
        annotations:
          summary: "Circuit breaker is open"
          description: "Circuit breaker {{ $labels.circuit_name }} is in OPEN state, indicating service degradation."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/circuit-breaker-open"

      # Database Query Performance Degradation
      - alert: DatabaseQueryPerformanceDegradation
        expr: |
          histogram_quantile(0.95, rate(auth_backend_database_query_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
          service: auth-backend
          category: performance
        annotations:
          summary: "Database query performance degradation"
          description: "95th percentile database query time is {{ $value | humanizeDuration }} for {{ $labels.orm }}/{{ $labels.operation }}."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/db-performance-degradation"

      # WebSocket Connection Issues
      - alert: WebSocketConnectionIssues
        expr: auth_backend_websocket_connections < 1
        for: 5m
        labels:
          severity: info
          service: auth-backend
          category: infrastructure
        annotations:
          summary: "No active WebSocket connections"
          description: "WebSocket connection count is {{ $value }}, which may indicate connectivity issues."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/websocket-issues"

      # Background Job Failures
      - alert: BackgroundJobFailures
        expr: |
          rate(auth_backend_background_jobs_total{status="error"}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: auth-backend
          category: infrastructure
        annotations:
          summary: "High background job failure rate"
          description: "Background job failure rate is {{ $value }} failures/second for job type {{ $labels.job_type }}."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/background-job-failures"

  - name: auth-backend-capacity
    rules:
      # High Request Volume
      - alert: HighRequestVolume
        expr: rate(auth_backend_http_requests_total[5m]) > 1000
        for: 5m
        labels:
          severity: info
          service: auth-backend
          category: capacity
        annotations:
          summary: "High request volume detected"
          description: "Request rate is {{ $value }} requests/second, approaching capacity limits."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/high-request-volume"

      # Database Connection Pool Exhaustion
      - alert: DatabaseConnectionPoolExhaustion
        expr: auth_backend_database_connections{state="active"} / auth_backend_database_connections{state="total"} > 0.9
        for: 2m
        labels:
          severity: warning
          service: auth-backend
          category: capacity
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Database connection pool utilization is {{ $value | humanizePercentage }} for pool {{ $labels.pool }}."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/db-connection-exhaustion"

      # Cache Memory Usage High
      - alert: CacheMemoryUsageHigh
        expr: auth_backend_cache_memory_usage_bytes > 800 * 1024 * 1024
        for: 5m
        labels:
          severity: warning
          service: auth-backend
          category: capacity
        annotations:
          summary: "High cache memory usage"
          description: "Cache memory usage is {{ $value | humanizeBytes }} for {{ $labels.cache_type }}, approaching limits."
          runbook_url: "https://docs.company.com/runbooks/auth-backend/cache-memory-high"